### ISSUE TITLE
Thanks for running with this ... examples please!

### ISSUE THREAD

**Issue by ColinEberhardt** [postman-open-technologies/bingchain#1]
ref: https://github.com/ColinEberhardt/langchain-mini/issues/2

Thanks for taking langchain-mini and running with it. Allowing the chain to call arbitrary APIs using the OpenAPI specification was on my list, but I didn't quite have enough time.

Also, I live the `script` tool, where you allow it to run code. There are many examples where LLMs struggle to perform certain tasks (often involving things like word counting, or output of certain length), but are quite capable of creating scripts that perform these tasks on their behalf. Allow them to actually execute the script seems a natural next step.

My one request is - some examples that demo these new tools :-)

**Comment by MikeRalphson** [comment]
Thanks for `langchain-mini`, we wouldn't have anything to go on if not for you @ColinEberhardt !

Example prompts is a great idea, I'll start adding some to the `README.md`.

Thanks again, and for the kind words.

**Comment by ColinEberhardt** [comment]
While you’re updating the docs, something else worth adding is the goals of this project.

For LangChain-mini, it was to demonstrate that ‘chain of reasoning’ orchestration is actually quite simple. 

I’m guessing for BingChain you’re wanting to go beyond that?

**Comment by MikeRalphson** [comment]
Examples added and README updated. Thanks again for the 'prompt'. 😁
